### PR TITLE
Feature/root cause spans 

### PR DESCRIPTION
**Pull request by shalom938**
addresses issues #270 and #271

### CODE REVIEW

**Review by arik-dig — CHANGES_REQUESTED** [review]
many classes were touched with no real need,
can you please revert the changes where there's an extra comma, whenever its the last declared field.

**Comment by shalom938** [comment]
> many classes were touched with no real need,
> can you please revert the changes where there's an extra comma, whenever its the last declared field.

I don't understand, you want to keep the redundant comma ?

**Comment by arik-dig** [comment]
> > many classes were touched with no real need,
> > can you please revert the changes where there's an extra comma, whenever its the last declared field.
> 
> I don't understand, you want to keep the redundant comma ?

yes please

**Comment by arik-dig** [comment]
@shalom938 is this relates to some open issue?
can you please link to it?

**Comment by shalom938** [comment]
related to 
Issues https://github.com/digma-ai/digma-intellij-plugin/issues/270  and https://github.com/digma-ai/digma-intellij-plugin/issues/271

**Comment by shalom938** [comment]
> related to
> Issues #270 and #271

related to
Issues https://github.com/digma-ai/digma-intellij-plugin/issues/270 and https://github.com/digma-ai/digma-intellij-plugin/issues/271

**Review by MykolaYaremchuk — APPROVED** [review]

**Pull request merged**
